// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Maximum Average Subarray I
// https://leetcode.com/problems/maximum-average-subarray-i/
// 

class Solution {
    public double findMaxAverage(int[] nums, int k) {
        double sum = 0;
        double maxavg = 0;
        for (int i = 0; i < k; i++) {
            sum += nums[i];
        }
        maxavg = sum / k;
        for (int i = k; i < nums.length; i++) {
            sum -= nums[i - k];
            sum += nums[i];
            maxavg = Math.max(maxavg, sum / k);
        }
        return maxavg;
    }
}

