# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Reverse Words in a String III
# https://leetcode.com/problems/reverse-words-in-a-string-iii/
# 

class Solution(object):
    def reverseWords(self, s):
        """
        :type s: str
        :rtype: str
        """
        tokens = s.split()
        for i in range(len(tokens)):
            tokens[i] = tokens[i][::-1]
        return " ".join(tokens)
            
            
        

