// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Maximum Depth of Binary Tree
// https://leetcode.com/problems/maximum-depth-of-binary-tree/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    private int max = 0;
    public int maxDepth(TreeNode root) {
        if (root == null) {
            return max;
        }
        helper(root, 1);
        return max;
    }
    private void helper(TreeNode root, int depth) {
        if (root == null) {
            return;
        }
        if (depth > max) {
            max = depth;
        }
        helper(root.left, depth + 1);
        helper(root.right, depth + 1);
        
    }
}

