// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Two Sum
// https://leetcode.com/problems/two-sum/
// 

class Solution {
    public int[] twoSum(int[] nums, int target) {
        if (nums == null || nums.length == 0) {
            return new int[0];
        }
        HashMap<Integer, Integer> hash = new HashMap<>();
        int[] result = new int[2];
        for (int i = 0; i < nums.length; i++) {
            if (hash.containsKey(target - nums[i])) {
                result[0] = hash.get(target - nums[i]);
                result[1] = i;
                return result;
            } else {
                hash.put(nums[i], i);
            }
        }
        return new int[0];
    }
}

