// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse String
// https://leetcode.com/problems/reverse-string/
// 

class Solution {
    public String reverseString(String s) {
        if (s == null || s.length() == 0) {
            return new String();
        }
        // error: Char -> char
        char[] c = s.toCharArray();
        int j = c.length - 1;
        for (int i = 0; i < c.length / 2; i++) {
            char temp = c[i];
            c[i] = c[j];
            c[j] = temp;
            j--;
        }
        return new String(c);
    }
}

