// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Range Sum Query - Immutable
// https://leetcode.com/problems/range-sum-query-immutable/
// 

class NumArray {
    private int[] prefixSum;
    public NumArray(int[] nums) {
        prefixSum = new int[nums.length + 1];
        int sum = 0;
        prefixSum[0] = 0;
        for (int i = 0; i < nums.length; i++) {
            sum += nums[i];
            prefixSum[i+1] = sum;
        }
    }
    
    public int sumRange(int i, int j) {
        return prefixSum[j+1] - prefixSum[i];
    }
}

/**
 * Your NumArray object will be instantiated and called as such:
 * NumArray obj = new NumArray(nums);
 * int param_1 = obj.sumRange(i,j);
 */

