// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Longest Substring Without Repeating Characters
// https://leetcode.com/problems/longest-substring-without-repeating-characters/
// 

class Solution {
    public int lengthOfLongestSubstring(String s) {
        if (s == null || s.length() == 0) {
            return 0;
        }
        HashSet<Character> map = new HashSet<>();
        int j = 0;
        int ans = 0;
        for (int i = 0; i < s.length(); i++) {
            while (j < s.length() && !map.contains(s.charAt(j))) {
                map.add(s.charAt(j));
                j++;
            }
            ans = Math.max(ans, map.size());
            map.remove(s.charAt(i));
        }
        return ans;
    }
}

