// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Remove Element
// https://leetcode.com/problems/remove-element/
// 

class Solution {
    public int removeElement(int[] nums, int val) {
        int left = 0; // left 及其左边都是非val的数
        int right = 0; // 快指针
        while (right < nums.length) {
            if (nums[right] != val) {
                int temp = nums[left];
                nums[left] = nums[right];
                nums[right] = temp;
                left++;
            }
            right++;
        }
        return left;
    }
}

