// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Implement strStr()
// https://leetcode.com/problems/implement-strstr/
// 

import java.lang.String.*;
class Solution {
    public int strStr(String haystack, String needle) {
        if (haystack == null || needle == null) {
            return -1;
        }
        for (int i = 0; i < haystack.length() - needle.length() + 1; i++) {
            int idx = i;
            int j;
            for (j = 0; j < needle.length(); j++) {
                if (haystack.charAt(idx) == needle.charAt(j)) {
                    idx++;
                } else {
                    break;
                }
            }
            if (j == needle.length()) {
                return i;
            }
        }
        return -1;
    }
}

