// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Path Sum
// https://leetcode.com/problems/path-sum/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public boolean hasPathSum(TreeNode root, int sum) {
        if (root == null) {
            return false;
        }
        return helper(root, sum, 0);
    }
    private boolean helper(TreeNode root, int sum, int result) {
        int temp = result + root.val;
        if (root.left == null && root.right == null) {
            if (temp == sum) {
                return true;
            } else {
                return false;
            }
        }
        boolean ans = false;
        if (root.left != null) {
            ans = ans || helper(root.left, sum, temp);
        }
        if (root.right != null) {
            ans = ans || helper(root.right, sum, temp);
        }
        return ans;
    }
}

