// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Combination Sum II
// https://leetcode.com/problems/combination-sum-ii/
// 

class Solution {
    public List<List<Integer>> combinationSum2(int[] candidates, int target) {
        List<List<Integer>> results = new ArrayList<>();
        if (candidates == null || candidates.length == 0) {
            return results;
        }
        Arrays.sort(candidates);
        helper(candidates, 0, target, new ArrayList<Integer>(), results);
        return results;
    }
    private void helper(int[] nums,
                        int startIndex,
                        int remain,
                        ArrayList<Integer> combination,
                        List<List<Integer>> results) {
        if (remain == 0) {
            results.add(new ArrayList<Integer>(combination));
        }
        for (int i = startIndex; i < nums.length; i++) {
            if (i != startIndex && nums[i] == nums[i - 1]) {
                continue;
            }
            if (remain - nums[i] >= 0) {
                combination.add(nums[i]);
                helper(nums, i + 1, remain - nums[i], combination, results);
                combination.remove(combination.size() - 1);
            }
        }
    }
}

