// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Longest Common Prefix
// https://leetcode.com/problems/longest-common-prefix/
// 

class Solution {
    public String longestCommonPrefix(String[] strs) {
        if (strs == null || strs.length == 0) {
            return new String();
        }
        for (int i = 0; i < strs[0].length(); i++) {
            char c = strs[0].charAt(i);
            for (int j = 1; j < strs.length; j++) {
                if (i == strs[j].length() || c != strs[j].charAt(i)) {// length limit or not equal
                    return strs[0].substring(0, i);
                }
            }
        }
        return strs[0];
        // method 1
        
        // String curt = strs[0];
        // for (int j = 1; j < strs.length; j++) {
        //     curt = helper(curt, strs[j]);
        // }
        // return curt;
        
    }
    
    // method 1
    
    // private String helper(String curt, String s) {
    //     int i;
    //     for (i = 0; i < Math.min(curt.length(), s.length()); i++) {
    //         if (curt.charAt(i) != s.charAt(i)) {
    //             break;
    //         }
    //     }
    //     return curt.substring(0, i); // i + 1 -> i
    // }
}

