// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Longest Absolute File Path
// https://leetcode.com/problems/longest-absolute-file-path/
// 

class Solution {
    public int lengthLongestPath(String input) {
        String[] tokens = input.split("\n");
        Stack<Integer> stack = new Stack<>();
        int longest = 0;
        int curLen = 0;
        for (String token : tokens) {
            int level = countLevel(token);
            int len = token.replaceAll("\t", "").length() + 1; // add "/"
            while (stack.size() > level) {
                curLen -= stack.pop();
            }
            curLen += len;
            
            
            if (token.contains(".")) { 
                longest = Math.max(longest, curLen - 1);
            }
            stack.push(len);
        }
        return longest;
    }
    private int countLevel(String s) {
        String r = s.replaceAll("\t", "");
        return s.length() - r.length();
    }
}

