// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Parentheses
// https://leetcode.com/problems/valid-parentheses/
// 

class Solution {
    public boolean isValid(String s) {
        if (s == null || s.length() == 0) {
            return true;
        }
        char[] str = s.toCharArray();
        Stack<Character> stack = new Stack<>();
        for (int i = 0; i < str.length; i++) {
            if (stack.empty()) {
                stack.push(str[i]);
                continue;
            }
            char current = (char) stack.pop();
            if (current == '(' && str[i] == ')') {
                continue;
            } else if (current == '[' && str[i] == ']') {
                continue;
            } else if (current == '{' && str[i] == '}') {
                continue;
            } else {
                stack.push(current);
                stack.push(str[i]);
            }
        }
        if (stack.empty()) {
            return true;
        }
        return false;
    }
}

