// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Moving Average from Data Stream
// https://leetcode.com/problems/moving-average-from-data-stream/
// 

class MovingAverage {

    /** Initialize your data structure here. */
    private int maxSize;
    private Queue<Integer> queue;
    private double sum; // double, not int
    public MovingAverage(int size) {
        maxSize = size;
        sum = 0.0;
        queue = new LinkedList<>();
    }
    
    public double next(int val) {
        if (queue.size() == maxSize) {
            sum -= queue.remove();
        }
        sum += val;
        queue.add(val);
        return sum / queue.size();
    }
}

/**
 * Your MovingAverage object will be instantiated and called as such:
 * MovingAverage obj = new MovingAverage(size);
 * double param_1 = obj.next(val);
 */

