// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Plus One
// https://leetcode.com/problems/plus-one/
// 

class Solution {
    public int[] plusOne(int[] digits) {
        if (digits == null || digits.length == 0) {
            return new int[0];
        }
        int carry = 1;
        int i = digits.length - 1;
        while (i >= 0 && carry == 1) {
            if (digits[i] == 9) {
                digits[i] = 0;
            } else {
                digits[i] += 1;
                carry = 0;
            }
            i--;
        }
        if (digits[0] != 0) {
            return digits;
        }
        int[] results = new int[digits.length + 1];
        results[0] = 1;
        for (i = 0; i < digits.length; i++) { // int i 外部已经定义了
            results[i + 1] = digits[i];
        }
        return results;
    }
}

