// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Binary Tree Paths
// https://leetcode.com/problems/binary-tree-paths/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
// divide and conquer
class Solution {
    public List<String> binaryTreePaths(TreeNode root) {
        List<String> result = new ArrayList<>();
        if (root == null) {
            return result;
        }
        
        List<String> left = binaryTreePaths(root.left);
        List<String> right = binaryTreePaths(root.right);
        
        for (String str : left) {
            result.add(root.val + "->" + str);
        }
        
        for (String str : right) {
            result.add(root.val + "->" + str);
        }
        
        if (result.isEmpty()) {
            result.add("" + root.val);
        }
        return result;
    }
}

