// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse String II
// https://leetcode.com/problems/reverse-string-ii/
// 

class Solution {
    public String reverseStr(String s, int k) {
        if (s == null || s.length() == 0) { // s.length
            return "";
        }
        char[] chararray = s.toCharArray();
        int i = 0;
        int j = Math.min(i + k - 1, chararray.length - 1);
        while (i < chararray.length) {
            swap(chararray, i, j);
            i += 2 * k;
            j = Math.min(i + k - 1, chararray.length - 1);
        }
        return String.valueOf(chararray);
        
    }
    private void swap(char[] chars, int start, int end) {
        while (start < end) {
            char temp = chars[start];
            chars[start] = chars[end];
            chars[end] = temp;
            start++;
            end--;
        }
    }
}

