// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Palindrome Number
// https://leetcode.com/problems/palindrome-number/
// 

class Solution {
    public boolean isPalindrome(int x) {
        if (x < 0) {
            return false;
        }
        int p = x;
        int q = 0;
        // WA: p > 10 -> p >= 10
        while (p >= 10) {
            q = q * 10 + p % 10;
            p = p / 10;
        }
        return q == x / 10 && p == x % 10;
    }
}

