// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Implement Trie (Prefix Tree)
// https://leetcode.com/problems/implement-trie-prefix-tree/
// 

class TrieNode {
    public boolean isEnd;
    private char c;
    public HashMap<Character, TrieNode> children = new HashMap<>();
    public TrieNode() {

    }
    public TrieNode(char c) {
        this.c = c;
    }
}
public class Trie {
    private TrieNode root;
    /** Initialize your data structure here. */
    public Trie() {
        root = new TrieNode();
    }

    /** Inserts a word into the trie. */
    public void insert(String word) {
        TrieNode p = root;
        char[] charArray = word.toCharArray();
        for (int i = 0; i < charArray.length; i++) {
            char cur = charArray[i];
            if (p.children.containsKey(cur)) {
                p = p.children.get(cur);
            } else {
                TrieNode newNode = new TrieNode(cur);
                p.children.put(cur, newNode);
                p = newNode;
            }
            if (i == charArray.length - 1) {
                p.isEnd = true;
            }
        }
    }

    /** Returns if the word is in the trie. */
    public boolean search(String word) {
        TrieNode result = searchWordNodePos(word);
        if (result != null && result.isEnd == true) {
            return true;
        }
        return false;
    }

    /** Returns if there is any word in the trie that starts with the given prefix. */
    public boolean startsWith(String prefix) {
        TrieNode result = searchWordNodePos(prefix);
        if (result !=  null) {
            return true;
        }
        return false;
    }

    public TrieNode searchWordNodePos(String word) {
        TrieNode p = root;
        char[] charArray = word.toCharArray();
        for (int i = 0; i < charArray.length; i++) {
            char cur = charArray[i];
            if (p.children.containsKey(cur)) {
                p = p.children.get(cur);
            } else {
                return null;
            }
        }
        return p;
    }
}


