// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Two Sum II - Input array is sorted
// https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/
// 

class Solution {
    public int[] twoSum(int[] numbers, int target) {
        int[] result = new int[2];
        if (numbers == null || numbers.length < 2) {
            return new int[0];
        }
        int front = 0;
        int end = numbers.length -1;
        while (front < end) {
            if (numbers[front] + numbers[end] == target) {
                result[0] = front + 1;
                result[1] = end + 1;
                return result;
            } else if (numbers[front] + numbers[end] < target) {
                front++;
            } else {
                end--;
            }
        }
        return result;
    }
}

