// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Single Number
// https://leetcode.com/problems/single-number/
// 

class Solution {
    public int singleNumber(int[] nums) {
        if (nums == null || nums.length == 0) {
            return -1;
        }
        Set<Integer> hash = new HashSet<>();
        for (int i = 0; i < nums.length; i++) {
            if (hash.contains(nums[i])) {
                hash.remove(nums[i]);
            } else {
                hash.add(nums[i]);
            }
        }
        int result = -1;
        for (Integer res : hash) {
            result = (int) res;
        }
        return result;
    }
}

