// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Closest Binary Search Tree Value
// https://leetcode.com/problems/closest-binary-search-tree-value/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public int closestValue(TreeNode root, double target) {
        int val = root.val;
        int kidVal = val;
        if (target < root.val) {
            if (root.left == null) {
                return val;
            }
            kidVal = closestValue(root.left, target);
        } else {
            if (root.right == null) {
                return val;
            }
            kidVal = closestValue(root.right, target);
        }
        if (Math.abs(kidVal - target) < Math.abs(val - target)) {
            return kidVal;
        }
        return val;
    }
}

